# Generated by Django 2.0.6 on 2018-06-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='enfermedad',
            field=models.ManyToManyField(to='interfaces.Enfermedad'),
        ),
    ]
