# Generated by Django 2.0.6 on 2018-06-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_auto_20180627_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparacion_hora',
            name='dia',
            field=models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado0'), (7, 'Domingo')], default=1, max_length=2),
        ),
    ]
