# Generated by Django 2.0.1 on 2018-06-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0004_paciente_max_permitido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
    ]
